### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by mansya** [ahfarmer/calculator#13]
Hi, @ahfarmer I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by ahfarmer** [comment]
Sounds great! Since the app itself is full screen, I would probably put the logo in the favicon and at the top of the readme (not in the body of the app itself). If that's OK with you, let's do it!

**Comment by mansya** [comment]
I have designed a logo for this project. do you like it ?
![calculator](https://user-images.githubusercontent.com/33461607/40865473-94e7b34e-6622-11e8-989b-d778a769b1ab.png)

**Comment by mansya** [comment]
is this application based on android?

**Comment by ahfarmer** [comment]
No - this is a web application that is a clone of the mac OS calculator.

I like the colorful one. 

Had another thought on this - since this is an open source project designed to help with learning, would you be willing to share the source for your design as well? Meaning the sketch or PSD file - not just the finished product.

**Comment by ahfarmer** [comment]
Fixed by https://github.com/ahfarmer/calculator/pull/15
